config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/about'
  get 'static_pages/home'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="en" data-bs-theme="dark">

  <head>
    <title>Web1st </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
  <%= render "partials/header" %>

<div class="container">
<% flash.each do |name, message| %>
<%= content_tag(:div, message, class: "alert alert-info#{name}") %>
  
<% end %>

    <%= yield %>

</div>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar bg-dark navbar-expand-lg border-bottom border-body" data-bs-theme="dark">

  <div class="container-fluid">
    <%= link_to "Web1st", static_pages_home_path, class: "navbar-brand"%>
          <span class="navbar-text d-lg-none">WebGoodCo</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-center px-4">
        <li class="nav-item">
         
            <%= link_to "Home", static_pages_home_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%=link_to "About", static_pages_about_path, class: "nav-link" %>
        </li>
              <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
         <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
  <% else %>
        <li class="nav-item">
          <%= link_to"Sign up", new_user_registration_path, class: "nav-link active"%>
        </li>
            <li class="nav-item">
          <%= link_to"Log in", new_user_session_path, class: "nav-link active"%>
        </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/static_pages/about.html.erb
<div class="row row-cols-1 row-cols-md-3">
  <div class="col">
    <div class="card">
  <%# <%= image_tag("card_01.svg", alt: "Example", size: "100%") %> %>

      <div class="card-body">
        <h5 class="card-title">Website Maintenance and Updates:</h5>
        <p class="card-text">We take care of all the essential updates, including content modifications, product additions, price changes, and any other necessary adjustments to keep your website current and relevant.</p>
      </div>
    </div>
  </div>
  <div class="col ">
    <div class="card scroll-animate">
  <%# <%= image_tag("card_02.svg", alt: "Example", size: "100%") %> %>
      <div class="card-body">
        <h5 class="card-title">Security Enhancements:</h5>
        <p class="card-text">Safeguarding your website from potential threats is our top priority. We continuously monitor and strengthen security measures to protect your valuable data and your visitors' information.</p>
      </div>  
    </div>
  </div>
  <div class="col">
    <div class="card">
   <%# <%= image_tag("card_03.svg", alt: "Example", size: "100%") %> %>
      <div class="card-body">
        <h5 class="card-title">Performance Optimization:</h5>
        <p class="card-text">Slow-loading websites can deter visitors and harm your search engine rankings. We optimize your website's speed and performance to ensure a seamless and user-friendly experience for all your visitors.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
        <%# <%= image_tag("card_04.svg", alt:"Backup and Recover", size:"100%") %> %>
      <div class="card-body">
        <h5 class="card-title">24/7 Monitoring:</h5>
        <p class="card-text">Our team is vigilant round the clock, tracking your website's uptime and availability. In case of any issues, we proactively address them to minimize downtime.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
    <%# <%= image_tag("card_05.svg", alt:"Backup and Recover", size:"100%") %> %>
      <div class="card-body">
        <h5 class="card-title">Backup and Recovery:</h5>
        <p class="card-text">Regular backups are performed to safeguard your website's data. In the unlikely event of data loss, we have robust recovery protocols in place to restore your site promptly.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
<%# <%= image_tag("card_06.svg", alt: "Search engine Optimization", size:"100%") %> %>
      <div class="card-body">
        <h5 class="card-title">Search Engine Optimization (SEO): </h5>
        <p class="card-text">We implement SEO best practices to improve your website's visibility and ranking on search engines, driving organic traffic and potential customers to your site.</p>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
   <div class="bg-dark">
   <% if user_signed_in? %>

   <h1 class="display-5 fw-bold">Welcome back!</h1>

       <div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div id="main-container" class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Web Management</h1>
        <p class="col-md-8 fs-4">Simplify your online life. We handle everything—updates, security, and performance. Focus on your business while we keep your website seamless and secure. Lets build something amazing !</p>
        <hr class="my-4">
        <%# <%= link_to 'Start Building', contacts_new_path, class: "btn btn-primary"%>
      </div>
    </div>
   <% else %>
                <div class="jumbotron">
                      <h1 class="display-4">Web Management</h1>
                      <p class="lead">Simplify your online life. We handle everything—updates, security, and performance. Focus on your business while we keep your website seamless and secure. Lets build something amazing !</p>
                      <hr class="my-4">
                      <p>Register to submit your project.</p>
                      <%= link_to "Register", new_user_registration_path, class: "btn btn-primary btn-lg"%>
                </div>
<% end %>
    <div class="row align-items-md-stretch pt-5">
      <div class="col-md-6">
        <div class="h-100 p-5 text-bg-dark rounded-3">
          <h2>Learn About Our Process</h2>
          <p>Certainly! Web development involves creating websites or web applications that cater to various user needs. Here's an in-depth breakdown of our web development process:</p>
          <button class="btn btn-outline-light" type="button">Learn more</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-body-tertiary border rounded-3">
          <h2>Got a project?</h2>
          <p>Empower your startup dreams with our donation-based web development service. We specialize in crafting dynamic websites for budding businesses. Your contribution fuels innovation and growth. Join us in building success!</p>
          <button class="btn btn-outline-secondary" type="button">Submit your project</button>
        </div>
      </div>
    </div>

   </div>
  